### ISSUE TITLE
check_env.py doesn't work on Python 3.4

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy4scipy2014#1]
I get this:

```
ERROR: TypeError: unorderable types: str() < int() [distutils.version]
Traceback (most recent call last):
  File "check_env.py", line 39, in <module>
    elif astropy_version < version.LooseVersion('0.4.0'):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/version.py", line 58, in __lt__
    c = self._cmp(other)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/distutils/version.py", line 343, in _cmp
    if self.version < other.version:
TypeError: unorderable types: str() < int()
```

**Comment by astrofrog** [comment]
cc @taldcroft

**Comment by taldcroft** [comment]
This was fixed.
